name: build-blog

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout theme repo
        uses: actions/checkout@v3
        with:
          repository: alexandrevicenzi/Flex
          path: theme
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python -m pip install -f requirements.txt
      - run: make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output