name: build-blog

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout theme repo
        uses: actions/checkout@v3
        with:
          repository: alexandrevicenzi/Flex
          path: ./flex-theme
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python -m pip install -r requirements.txt
      - run: make html
      - name: upload output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./output
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
